#! /bin/sh

sxhkd &
picom &
export _JAVA_AWT_WM_NONREPARENTING=1 &
/home/lightkeima/.config/polybar/launch.sh &
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        10

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Pink
bspc config normal_border_color "#777777"
bspc config active_border_color "#C6B5D6"
bspc config focused_border_color "#C6B5D6"

# White
#bspc config normal_border_color "#777777"
#bspc config active_border_color "#FFFFFF"
#bspc config focused_border_color "#FFFFFF"

# Light brown
#bspc config normal_border_color "#564E54"
#bspc config active_border_color "
#bspc config focused_border_color "#AE8876"

# Brown
#bspc config normal_border_color "#312210"
#bspc config active_border_color "#896B65"
#bspc config focused_border_color "#896B65"

#bspc config presel_border_color "#7F8C8D"


